[project]
name = "whisper-live"
version = "0.1.0"
description = "A simple single-page Web app showing live captions."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cmake>=4.2.1",
    "librosa>=0.11.0",
]
